#!/bin/sh

pid=$(pgrep autotiling)
if [ -z "$pid" ]; then
    notify-send -u low -t 1000 "Autotiling enabled"
    autotiling
else
    killall autotiling
    notify-send -u critical -t 1000 "Autotiling disabled"
fi
