game_dir = "/home/rai/dev/factorio/1"
mods_dir = "/home/rai/dev/factorio/linked/mods"

# [portal]
# token = "12345"
# username = "raiguard"

[sets]
Autopilot = ["Autopilot", "EditorExtensions", "Sandbox"]
EditorExtensions = ["EditorExtensions", "Sandbox"]
Krastorio2 = ["Krastorio2", "EditorExtensions", "Sandbox"]
LtnManager = ["LtnManager", "EditorExtensions", "Sandbox"]
RateCalculator = ["RateCalculator", "EditorExtensions", "Sandbox"]
RecipeBook = ["RecipeBook", "EditorExtensions", "Sandbox"]
TaskList = ["TaskList", "Todo-List", "EditorExtensions", "Sandbox"]
