auto_download = true
game_dir = "/home/rai/dev/factorio/1"
mods_dir = "/home/rai/dev/factorio/linked/mods"
sync_latest_versions = true

[sets]
AdvancedEntityPaste = ["AdvancedEntityPaste", "EditorExtensions", "Sandbox"]
Autopilot = ["Autopilot", "EditorExtensions", "Sandbox"]
CursorEnhancements = ["CursorEnhancements", "EditorExtensions", "Sandbox"]
EditorExtensions = ["EditorExtensions", "Sandbox"]
Krastorio2 = ["Krastorio2", "EditorExtensions", "Sandbox"]
LtnManager = ["LtnManager", "EditorExtensions", "Sandbox"]
RateCalculator = ["RateCalculator", "EditorExtensions", "Sandbox"]
RecipeBook = ["RecipeBook", "EditorExtensions", "Sandbox"]
TaskList = ["TaskList", "Todo-List", "EditorExtensions", "Sandbox"]
