game_dir = "/home/rai/dev/factorio/1.1"

[sets]
bpt = ["BlueprintTools", "EditorExtensions", "flib"]
bnl = ["BottleneckLite", "EditorExtensions", "flib"]
ce = ["CursorEnhancements", "EditorExtensions", "flib"]
ee = ["EditorExtensions", "flib"]
fmf = ["FluidMustFlow", "EditorExtensions", "flib"]
k2 = ["Krastorio2", "EditorExtensions", "flib"]
pvis = ["PipeVisualizer", "EditorExtensions", "flib"]
qis = ["QuickItemSearch", "EditorExtensions", "flib"]
rc = ["RateCalculator", "EditorExtensions", "flib"]
rb = ["RecipeBook", "EditorExtensions", "FNEI", "what-is-it-really-used-for", "flib"]
tl = ["Tapeline", "EditorExtensions", "flib"]
tlist = ["TaskList", "Todo-List", "EditorExtensions", "flib"]
tg = ["TrainGroups", "Train_Control_Signals", "EditorExtensions", "flib"]
urq = ["UltimateResearchQueue", "EditorExtensions", "flib"]
