game_dir = "/home/rai/dev/factorio/1"
mods_dir = "/home/rai/dev/factorio/linked/mods"

[sets]
AdjustableInserters = ["AdjustableInserters", "bobinserters", "EditorExtensions"]
AdvancedEntityPaste = ["AdvancedEntityPaste", "EditorExtensions"]
Autopilot = ["Autopilot", "EditorExtensions"]
BeltVisualizer = ["BeltVisualizer", "EditorExtensions"]
BlueprintTools = ["BlueprintTools", "EditorExtensions"]
BottleneckLite = ["BottleneckLite", "EditorExtensions"]
CursorEnhancements = ["CursorEnhancements", "EditorExtensions"]
EditorExtensions = ["EditorExtensions"]
FluidMustFlow = ["FluidMustFlow", "EditorExtensions"]
Krastorio2 = ["Krastorio2", "EditorExtensions"]
LtnManager = ["LtnManager", "EditorExtensions"]
PipeVisualizer = ["PipeVisualizer", "EditorExtensions"]
QuickItemSearch = ["QuickItemSearch", "EditorExtensions"]
RaiRibbonMaze = ["RaiRibbonMaze", "EditorExtensions"]
RateCalculator = ["RateCalculator", "EditorExtensions"]
RecipeBook = ["RecipeBook", "EditorExtensions", "FNEI", "what-is-it-really-used-for"]
Tapeline = ["Tapeline", "EditorExtensions"]
TaskList = ["TaskList", "Todo-List", "EditorExtensions"]
TrainGroups = ["TrainGroups", "Train_Control_Signals", "EditorExtensions"]
UltimateResearchQueue = ["UltimateResearchQueue", "EditorExtensions"]
