auto_download = true
game_dir = "/home/rai/dev/factorio/1"
mods_dir = "/home/rai/dev/factorio/linked/mods"
sync_latest_versions = true
sync_startup_settings = true

[sets]
AdjustableInserters = ["AdjustableInserters", "bobinserters", "EditorExtensions", "Sandbox", "flib"]
AdvancedEntityPaste = ["AdvancedEntityPaste", "EditorExtensions", "Sandbox", "flib"]
Autopilot = ["Autopilot", "EditorExtensions", "Sandbox", "flib"]
BeltVisualizer = ["BeltVisualizer", "EditorExtensions", "Sandbox", "flib"]
CursorEnhancements = ["CursorEnhancements", "EditorExtensions", "Sandbox", "flib"]
EditorExtensions = ["EditorExtensions", "Sandbox", "flib"]
FluidMustFlow = ["FluidMustFlow", "EditorExtensions", "Sandbox", "flib"]
Krastorio2 = ["Krastorio2", "Krastorio2Assets", "EditorExtensions", "Sandbox", "flib"]
LtnManager = ["LtnManager", "EditorExtensions", "Sandbox", "flib"]
PipeVisualizer = ["PipeVisualizer", "EditorExtensions", "Sandbox", "flib"]
QuickItemSearch = ["QuickItemSearch", "EditorExtensions", "Sandbox", "flib"]
RaiRibbonMaze = ["RaiRibbonMaze", "EditorExtensions", "Sandbox", "flib"]
RateCalculator = ["RateCalculator", "EditorExtensions", "Sandbox", "flib"]
RecipeBook = ["RecipeBook", "EditorExtensions", "Sandbox", "flib"]
Tapeline = ["Tapeline", "EditorExtensions", "Sandbox", "flib"]
TaskList = ["TaskList", "Todo-List", "EditorExtensions", "Sandbox", "flib"]
TrainGroups = ["TrainGroups", "Train_Control_Signals", "EditorExtensions", "Sandbox", "flib"]
UltimateResearchQueue = ["UltimateResearchQueue", "sonaxaton-research-queue", "EditorExtensions", "Sandbox", "flib"]
