evaluate-commands %sh{
    cork init
    kks init
    kak-lsp --kakoune -s $kak_session
}

try %{ source "~/dev/projects/personal/pesticide/rc/pesticide.kak" }

# --------------------------------------------------
# PLUGINS

cork auto-pairs.kak "https://github.com/alexherbo2/auto-pairs.kak"

cork fzf.kak "https://github.com/andreyorst/fzf.kak" %{
    require-module fzf-grep
    set-option global fzf_terminal_command 'terminal-floating kak -c %val{session} -e "%arg{@}"'
}

cork harpoon.kak "https://git.sr.ht/~raiguard/harpoon.kak" %{
    harpoon-add-bindings
}

cork kak-move-lines "https://git.sr.ht/~raiguard/kak-move-lines" %{
    map global normal ⓙ ': move-lines-down %val{count}<ret>'
    map global normal <c-k> ': move-lines-up %val{count}<ret>'
}

cork kak-rainbower "https://github.com/crizan/kak-rainbower" %{
    set-option global rainbow_mode 0
    set-option global rainbow_check_templates Y
}

cork kakoune-fandt "https://github.com/listentolist/kakoune-fandt" %{
    require-module fandt

    hook global ModeChange push:.*:user.fandt %{
        set-face window PrimarySelection ",rgba:%opt{lightorange}%opt{selectionalpha}"
        set-face window PrimaryCursor ",rgba:%opt{lightorange}%opt{cursoralpha}"
        set-face window SecondarySelection ",rgba:%opt{darkorange}%opt{selectionalpha}"
        set-face window SecondaryCursor ",rgba:%opt{darkorange}%opt{cursoralpha}"
    }

    hook global ModeChange pop:user.fandt:.* %{
        set-face window PrimarySelection ",rgba:%opt{blue}%opt{selectionalpha}"
        set-face window PrimaryCursor ",rgba:%opt{blue}%opt{cursoralpha}"
        set-face window SecondarySelection ",rgba:%opt{green}%opt{selectionalpha}"
        set-face window SecondaryCursor ",rgba:%opt{green}%opt{cursoralpha}"
    }
}

cork kakoune-focus "https://github.com/caksoylar/kakoune-focus" %{
    map global user <space> ': focus-toggle<ret>' -docstring "toggle selections focus"
}

cork kakoune-grep-write "https://github.com/JacobTravers/kakoune-grep-write" %{
    hook global BufCreate \*grep\* %{
        alias buffer w grep-write
    }
}

cork kakoune-inc-dec "https://gitlab.com/Screwtapello/kakoune-inc-dec" %{
    map global normal = ": inc-dec-modify-numbers - 1<ret>"
    map global normal + ": inc-dec-modify-numbers + 1<ret>"
}

cork kakoune-snippets "https://github.com/CharlesGueunet/kakoune-snippets"

cork kakoune-sort-selections "https://github.com/occivink/kakoune-sort-selections"

cork kakoune-state-save "https://gitlab.com/Screwtapello/kakoune-state-save"

cork kakoune-sudo-write "https://github.com/occivink/kakoune-sudo-write"

cork local-kakrc "https://github.com/dgmulf/local-kakrc" %{
    set-option global source_local_kakrc true
}

cork mark.kak "https://github.com/alexherbo2/mark.kak"

cork pmanage.kak "https://github.com/andreyorst/pmanage.kak"

cork smarttab.kak "https://github.com/andreyorst/smarttab.kak"

cork surround.kak "https://github.com/alexherbo2/surround.kak" %{
    map global normal "'" ": enter-user-mode surround<ret>"
}

# --------------------------------------------------
# GENERAL

# Color scheme
colorscheme one-darker
one-enable-fancy-underlines
# Mark.kak faces
set-face global MarkedPrimaryCursor "default,rgba:%opt{magenta}%opt{cursoralpha}"
set-face global MarkedPrimarySelection "default,rgba:%opt{magenta}%opt{selectionalpha}"
set-face global MarkedSecondaryCursor "default,rgba:%opt{magenta}%opt{cursoralpha}"
set-face global MarkedSecondarySelection "default,rgba:%opt{magenta}%opt{selectionalpha}"
# Trailing whitespace
add-highlighter global/trailing-whitespaces regex "(\h+)$" "1:default,rgba:%opt{darkred}%opt{selectionalpha}"
# Highlighters
add-highlighter global/ number-lines -relative -separator " " -hlcursor
add-highlighter global/ show-matching

# UI settings
set-option global ui_options terminal_assistant=off terminal_set_title=false
set-option global startup_info_version 10000000000000 # Don't show changelog
set-option global scrolloff 100,5 # Always center cursor vertically

# Auto-reload please
set-option global autoreload yes

# Use ripgrep instead of grep
set-option global grepcmd 'rg -Hn --no-heading --sort path --vimgrep'

# Make kks work as a stand-in for kcr
alias global connect kks-connect

# --------------------------------------------------
# OTHERS

source "%val{config}/commands.kak"
source "%val{config}/hooks.kak"
source "%val{config}/keybindings.kak"
source "%val{config}/lsp.kak"
source "%val{config}/replace-mode.kak"
source "%val{config}/status-line.kak"
source "%val{config}/todo.kak"
