gui:
  showCommandLog: false
  showFileTree: false
  showIcons: true
  theme:
    selectedLineBgColor:
      - '#2a3f53'
    selectedRangeBgColor:
      - reverse

keybinding:
  universal:
    nextPage: '<c-f>'
    prevPage: '<c-b>'

os:
  editCommand: 'kks edit'
