gui:
  showCommandLog: false
  showFileTree: false
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

keybinding:
  universal:
    nextPage: '<c-f>'
    prevPage: '<c-b>'
