gui:
  # showCommandLog: false
  showFileTree: false
  theme:
    selectedLineFgColor:
      - default
    selectedLineBgColor:
      - '#2a3f53'
    selectedRangeBgColor:
      - reverse

keybinding:
  universal:
    nextPage: '<c-f>'
    prevPage: '<c-b>'

os:
  edit: 'kak {{filename}}'
