gui:
  showCommandLog: false
  showFileTree: false
  theme:
    selectedLineBgColor:
      - '#2a3f53'

keybinding:
  universal:
    nextPage: '<c-f>'
    prevPage: '<c-b>'

os:
  editCommand: 'kks edit'
