# GENERAL

verbosity = 2

# LANGUAGES

[language.bash]
filetypes = ["sh"]
roots = [".git", ".hg"]
command = "bash-language-server"
args = ["start"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd", ".git", ".hg"]
command = "clangd"
args = ["--limit-references=0", "--header-insertion=never", "--pch-storage=memory"]

[language.css]
filetypes = ["css"]
roots = ["package.json", ".git", ".hg"]
command = "vscode-css-languageserver"
args = ["--stdio"]

[language.factorio-changelog]
filetypes = ["factorio-changelog"]
roots = ["changelog.txt"]
command = "fmtk"
args = ["lsp", "--stdio"]

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"

[language.hare]
filetypes = ["hare"]
roots = [".git/", "Makefile", "hare.ini"]
command = "harepls"

[language.java]
filetypes = ["java"]
roots = [".git/", "Makefile"]
command = "jdtls"

[language.java.settings]
# See https://github.dev/eclipse/eclipse.jdt.ls
"java.format.insertSpaces" = true

[language.json]
filetypes = ["json"]
roots = ["info.json", "package.json"]
command = "vscode-json-languageserver"
args = ["--stdio"]

[language.json.settings.json]
format.enable = true

[[language.json.settings.json.schemas]]
fileMatch = ["info.json"]
url = "file:///usr/lib/node_modules/factoriomod-debug/schema/modinfo.json"

[language.latex]
filetypes = ["tex", "latex"]
roots = [".git/"]
command = "texlab"

[language.latex.settings.texlab]
build.args = ["--pdf", "%f"]

[language.lua]
filetypes = ["lua"]
roots = [".git/"]
command = "/home/rai/dev/personal/luapls/luapls"
args = ["lsp"]

# [language.lua]
# filetypes = ["lua"]
# roots = [".git/"]
# command = "lua-language-server"
# args = ["--logpath=/home/rai/.local/share/lua-language-server/log"]

[language.lua.settings.Lua]
diagnostics.disable = ["lowercase-global", "redefined-local"]
diagnostics.severity = { unused-local = "Error", undefined-global = "Error", undefined-field = "Error" }
hover.expandAlias = false
hover.previewFields = 0
semantic.enable = false
telemetry.enable = false
workspace.userThirdParty = ["/home/rai/dev/luals"]

[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pylsp"

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"

[language.rust.settings.rust-analyzer]
checkOnSave.command = "clippy"

[language.scss]
filetypes = ["scss"]
roots = ["package.json", ".git", ".hg"]
command = "vscode-css-languageserver"
args = ["--stdio"]

[language.tsx]
filetypes = ["typescript"]
roots = ["package.json"]
offset_encoding = "utf-8"
command = "typescript-language-server"
args = ['--stdio']

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "zls"

# SEMANTIC TOKENS

[[semantic_tokens]]
token = "formatSpecifier"
face = "operator"

[[semantic_tokens]]
token = "lifetime"
face = "attribute"

[[semantic_tokens]]
token = "macro"
face = "value"

[[semantic_tokens]]
token = "macroBang"
face = "value"

[[semantic_tokens]]
token = "method"
face = "function"

[[semantic_tokens]]
token = "regexp"
face = "value"

[[semantic_tokens]]
token = "variable"
face = "+s@variable"
modifiers = ["consuming"]

[[semantic_tokens]]
token = "variable"
face = "value"
modifiers = ["globalScope"]
